export const ingredients = [
  "Beras putih", "Beras merah", "Beras hitam", "Beras ketan putih", "Beras ketan hitam",
  "Tepung terigu protein tinggi", "Tepung terigu protein sedang", "Tepung terigu protein rendah",
  "Tepung beras", "Tepung ketan", "Tepung tapioka", "Tepung maizena", "Tepung sagu", "Tepung mocaf",
  "Tepung jagung", "Tepung hunkwe", "Tepung panir", "Tepung roti", "Oat", "Havermut",
  "Jagung", "Kentang", "Ubi jalar", "Singkong", "Talas", "Garut", "Ganyong",
  "Roti tawar", "Roti gandum", "Tortilla",
  "Mie telur", "Mie kuning", "Mie instan", "Bihun", "Soun", "Kwetiau",
  "Ayam broiler", "Ayam kampung", "Dada ayam", "Paha ayam", "Sayap ayam", "Ceker ayam",
  "Hati ayam", "Ampela ayam", "Kulit ayam",
  "Daging sapi", "Has dalam", "Has luar", "Sandung lamur", "Sengkel", "Iga sapi", "Lidah sapi",
  "Babat", "Paru sapi", "Hati sapi", "Jantung sapi", "Buntut sapi",
  "Daging kambing", "Iga kambing", "Hati kambing",
  "Bebek", "Dada bebek", "Paha bebek",
  "Tuna", "Tongkol", "Cakalang", "Kembung", "Bandeng", "Kakap", "Gurame", "Tenggiri", "Bawal",
  "Salmon", "Sarden", "Lemuru", "Selar", "Layang",
  "Lele", "Nila", "Patin", "Mujair", "Gabus", "Ikan mas",
  "Udang", "Kepiting", "Rajungan", "Cumi-cumi", "Sotong",
  "Kerang hijau", "Kerang dara", "Kerang bambu", "Tiram", "Lobster",
  "Telur ayam", "Telur ayam kampung", "Telur bebek", "Telur puyuh", "Telur asin",
  "Tahu putih", "Tahu kuning", "Tahu sutra", "Tahu pong", "Tahu Jepang",
  "Tempe", "Tempe gembus", "Oncom",
  "Bayam", "Kangkung", "Sawi hijau", "Sawi putih", "Pakcoy", "Kailan", "Selada",
  "Daun singkong", "Daun pepaya", "Daun kelor", "Genjer",
  "Wortel", "Buncis", "Kacang panjang", "Terong ungu", "Terong hijau",
  "Labu siam", "Labu kuning", "Oyong", "Gambas", "Timun", "Pare",
  "Tomat", "Paprika merah", "Paprika hijau", "Paprika kuning",
  "Jamur tiram", "Jamur kuping", "Jamur kancing", "Jamur enoki", "Jamur shiitake", "Jamur merang",
  "Bawang merah", "Bawang putih", "Bawang bombai",
  "Cabai merah besar", "Cabai merah keriting", "Cabai rawit merah", "Cabai rawit hijau", "Cabai hijau besar",
  "Jahe", "Lengkuas", "Kunyit", "Kencur", "Serai",
  "Daun salam", "Daun jeruk", "Daun pandan", "Kemangi", "Seledri", "Daun bawang",
  "Ketumbar", "Merica putih", "Merica hitam", "Jinten", "Kapulaga", "Kayu manis", "Cengkih",
  "Bunga lawang", "Pala", "Wijen", "Kemiri", "Asam jawa",
  "Garam", "Gula pasir", "Gula merah", "Gula aren",
  "Kaldu ayam", "Kaldu sapi", "Kaldu jamur", "Penyedap rasa",
  "Kecap manis", "Kecap asin", "Saus tiram", "Saus ikan", "Saus tomat", "Saus sambal",
  "Mayones", "Mustard", "Cuka makan",
  "Minyak wijen", "Minyak goreng", "Minyak kelapa", "Minyak zaitun", "Minyak kanola",
  "Margarin", "Mentega", "Shortening",
  "Susu UHT", "Susu segar", "Susu evaporasi", "Susu kental manis", "Susu bubuk",
  "Keju cheddar", "Keju mozzarella", "Keju parmesan", "Yogurt", "Whipping cream", "Butter",
  "Kedelai", "Kacang tanah", "Kacang hijau", "Kacang merah", "Kacang hitam",
  "Kacang mede", "Almond", "Walnut", "Pistachio",
  "Pisang", "Mangga", "Pepaya", "Nanas", "Jambu biji", "Jambu air",
  "Semangka", "Melon", "Jeruk", "Salak", "Rambutan", "Durian", "Manggis", "Sawo",
  "Kedondong", "Belimbing", "Alpukat", "Apel", "Pir", "Kiwi", "Anggur",
  "Stroberi", "Blueberry", "Lemon", "Kurma", "Kismis", "Granola", "Sereal",
  "Sosis", "Nugget", "Bakso", "Kornet", "Dendeng", "Abon", "Smoked beef", "Ham ayam", "Ham sapi",
  "Tauco", "Terasi", "Tape singkong", "Tape ketan",
  "Kerupuk", "Emping", "Bawang goreng", "Sambal", "Acar", "Serundeng", "Cabai bubuk", "Boncabe",
]
